version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn data_dashboard_bi.wsgi:application --bind 0.0.0.0:8000 --workers 5"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DOMAIN=${DOMAIN}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
    restart: always

  nginx_server:
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
      - .:/code
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - web
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - nginx_server
    environment:
      - DOMAIN=${DOMAIN}
    command: >
      certonly --webroot --webroot-path=/var/www/certbot
      --register-unsafely-without-email --agree-tos --no-eff-email
      --force-renewal
      -d ${DOMAIN}
